import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";
import JSZip from "jszip";
import FileSaver from "file-saver";
const { saveAs } = FileSaver;
import { generateWebsite, type TemplateName } from "@/lib/website-generator";
import {
  listProjects,
  saveProject,
  deleteProject,
  type Project,
} from "@/lib/projects-store";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "مصمم المواقع الذكي | Smart Website Designer" },
      {
        name: "description",
        content:
          "صف موقعك بالعربية أو الإنجليزية واحصل على HTML جاهز فوراً مع معاينة مباشرة، قوالب متعددة، حفظ المشاريع وتصديرها كـ ZIP.",
      },
      { property: "og:title", content: "مصمم المواقع الذكي" },
      {
        property: "og:description",
        content: "ولّد مواقع جاهزة من وصف نصي مع معاينة فورية وتصدير ZIP.",
      },
    ],
  }),
  component: Index,
});

const EXAMPLES = [
  "موقع لمطعم عربي يحتوي على شريط علوي وقائمة طعام وصور ونموذج تواصل، باللون الأخضر",
  "Landing page for a SaaS product with hero, features cards, pricing table and contact form",
  "موقع شركة تقنية باللون الأزرق مع قائمة خدمات ومعرض صور وتذييل",
];

function Index() {
  const [description, setDescription] = useState<string>(EXAMPLES[0]);
  const [template, setTemplate] = useState<TemplateName>("default");
  const [html, setHtml] = useState<string>("");
  const [projects, setProjects] = useState<Project[]>([]);
  const [projectName, setProjectName] = useState<string>("");
  const [tab, setTab] = useState<"preview" | "code" | "projects">("preview");
  const iframeRef = useRef<HTMLIFrameElement>(null);

  useEffect(() => {
    setProjects(listProjects());
    handleGenerate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleGenerate = () => {
    const code = generateWebsite(description, template);
    setHtml(code);
  };

  const handleSave = () => {
    const name = projectName.trim() || description.slice(0, 40) || "مشروع";
    const p: Project = {
      id: crypto.randomUUID(),
      name,
      description,
      template,
      html,
      createdAt: Date.now(),
    };
    saveProject(p);
    setProjects(listProjects());
    setProjectName("");
  };

  const handleLoad = (p: Project) => {
    setDescription(p.description);
    setTemplate(p.template as TemplateName);
    setHtml(p.html);
    setTab("preview");
  };

  const handleDelete = (id: string) => {
    deleteProject(id);
    setProjects(listProjects());
  };

  const handleExportZip = async (p?: Project) => {
    const target = p ?? {
      name: projectName.trim() || "website",
      html,
      description,
    };
    const zip = new JSZip();
    zip.file("index.html", target.html);
    zip.file("description.txt", target.description);
    zip.file(
      "README.md",
      `# ${target.name}\n\nGenerated by Smart Website Designer.\n\nOpen \`index.html\` in any browser.\n`,
    );
    const blob = await zip.generateAsync({ type: "blob" });
    saveAs(blob, `${target.name.replace(/[^a-zA-Z0-9\u0600-\u06FF_-]+/g, "_")}.zip`);
  };

  const handleDownloadHtml = () => {
    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    saveAs(blob, "index.html");
  };

  const handleOpenInNewTab = () => {
    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    window.open(url, "_blank");
    setTimeout(() => URL.revokeObjectURL(url), 60_000);
  };

  const previewSrc = useMemo(() => {
    return "data:text/html;charset=utf-8," + encodeURIComponent(html);
  }, [html]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-blue-50">
      {/* Header */}
      <header className="border-b border-slate-200 bg-white/80 backdrop-blur sticky top-0 z-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center text-white font-bold shadow-lg shadow-blue-500/30">
              W
            </div>
            <div>
              <h1 className="text-base sm:text-lg font-bold text-slate-900">
                مصمم المواقع الذكي
              </h1>
              <p className="text-xs text-slate-500">
                Smart Website Designer · AR / EN
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Link
              to="/ai-lab"
              className="text-sm px-3 py-2 rounded-lg bg-gradient-to-br from-fuchsia-500 to-indigo-600 text-white shadow-md hover:opacity-95"
            >
              🧠 مختبر الذكاء
            </Link>
            <button
              onClick={handleOpenInNewTab}
              disabled={!html}
              className="hidden sm:inline-flex text-sm px-3 py-2 rounded-lg border border-slate-300 hover:bg-slate-50 disabled:opacity-50"
            >
              فتح في نافذة
            </button>
            <button
              onClick={handleDownloadHtml}
              disabled={!html}
              className="text-sm px-3 py-2 rounded-lg border border-slate-300 hover:bg-slate-50 disabled:opacity-50"
            >
              HTML
            </button>
            <button
              onClick={() => handleExportZip()}
              disabled={!html}
              className="text-sm px-3 py-2 rounded-lg bg-slate-900 text-white hover:bg-slate-800 disabled:opacity-50"
            >
              تصدير ZIP
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-[1500px] mx-auto px-4 sm:px-6 py-6 grid lg:grid-cols-[42%_58%] gap-6">
        {/* Left panel */}
        <aside className="space-y-4">
          <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm">
            <label className="block text-sm font-semibold text-slate-900 mb-2">
              📝 صف موقعك (عربي أو إنجليزي)
            </label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              rows={6}
              className="w-full text-sm rounded-xl border border-slate-300 p-3 focus:border-blue-500 focus:ring-2 focus:ring-blue-100 outline-none resize-none"
              placeholder="مثال: موقع لمطعم باللون الأخضر مع شريط علوي ونموذج تواصل..."
            />

            <div className="flex flex-wrap gap-2 mt-2">
              {EXAMPLES.map((ex, i) => (
                <button
                  key={i}
                  onClick={() => setDescription(ex)}
                  className="text-xs px-2.5 py-1 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-700"
                >
                  مثال {i + 1}
                </button>
              ))}
            </div>

            <div className="grid grid-cols-2 gap-3 mt-4">
              <div>
                <label className="block text-xs font-medium text-slate-600 mb-1">
                  🎨 القالب
                </label>
                <select
                  value={template}
                  onChange={(e) => setTemplate(e.target.value as TemplateName)}
                  className="w-full text-sm rounded-lg border border-slate-300 px-3 py-2 bg-white"
                >
                  <option value="default">Default (Modern)</option>
                  <option value="bootstrap">Bootstrap 5</option>
                  <option value="tailwind">Tailwind CDN</option>
                </select>
              </div>
              <div>
                <label className="block text-xs font-medium text-slate-600 mb-1">
                  💾 اسم المشروع
                </label>
                <input
                  value={projectName}
                  onChange={(e) => setProjectName(e.target.value)}
                  placeholder="my-site"
                  className="w-full text-sm rounded-lg border border-slate-300 px-3 py-2"
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-2 mt-4">
              <button
                onClick={handleGenerate}
                className="text-sm font-semibold px-4 py-2.5 rounded-xl bg-gradient-to-br from-blue-600 to-indigo-600 text-white shadow-md shadow-blue-500/30 hover:opacity-95"
              >
                🚀 توليد الموقع
              </button>
              <button
                onClick={handleSave}
                disabled={!html}
                className="text-sm font-semibold px-4 py-2.5 rounded-xl bg-amber-500 text-white shadow-md shadow-amber-500/30 hover:bg-amber-600 disabled:opacity-50"
              >
                💾 حفظ
              </button>
            </div>
          </div>

          <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm">
            <h3 className="text-sm font-semibold text-slate-900 mb-2">
              💼 المشاريع المحفوظة ({projects.length})
            </h3>
            {projects.length === 0 ? (
              <p className="text-xs text-slate-500 py-4 text-center">
                لا توجد مشاريع بعد. ولّد موقعاً واضغط حفظ.
              </p>
            ) : (
              <ul className="space-y-2 max-h-72 overflow-auto -mx-1 px-1">
                {projects.map((p) => (
                  <li
                    key={p.id}
                    className="border border-slate-200 rounded-lg p-2.5 hover:bg-slate-50 group"
                  >
                    <div className="flex items-center justify-between gap-2">
                      <button
                        onClick={() => handleLoad(p)}
                        className="text-sm font-medium text-slate-900 text-right truncate flex-1"
                      >
                        {p.name}
                      </button>
                      <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                        <button
                          onClick={() => handleExportZip(p)}
                          title="تصدير"
                          className="text-xs px-2 py-1 rounded hover:bg-slate-200"
                        >
                          📦
                        </button>
                        <button
                          onClick={() => handleDelete(p.id)}
                          title="حذف"
                          className="text-xs px-2 py-1 rounded hover:bg-red-100 text-red-600"
                        >
                          🗑
                        </button>
                      </div>
                    </div>
                    <p className="text-[11px] text-slate-500 mt-0.5 truncate">
                      {p.template} · {new Date(p.createdAt).toLocaleString()}
                    </p>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </aside>

        {/* Right panel — TV screen preview */}
        <section className="flex flex-col">
          <div className="relative rounded-[28px] p-5 sm:p-6 bg-gradient-to-br from-zinc-900 via-zinc-800 to-zinc-900 shadow-[0_25px_60px_-15px_rgba(0,0,0,0.6)] border border-zinc-700">
            {/* TV bezel top controls */}
            <div className="flex items-center justify-between mb-3 px-1">
              <div className="flex items-center gap-2">
                <span className="w-3 h-3 rounded-full bg-red-500 shadow-[0_0_8px_rgba(239,68,68,0.7)]" />
                <span className="w-3 h-3 rounded-full bg-yellow-400" />
                <span className="w-3 h-3 rounded-full bg-green-500" />
                <span className="ml-2 text-[11px] text-zinc-400 font-mono">LIVE · شاشة المعاينة</span>
              </div>
              <div className="flex gap-1 bg-zinc-950/60 rounded-lg p-1">
                {(["preview", "code"] as const).map((t) => (
                  <button
                    key={t}
                    onClick={() => setTab(t)}
                    className={`text-xs px-3 py-1 rounded-md font-medium transition ${
                      tab === t
                        ? "bg-zinc-100 text-zinc-900"
                        : "text-zinc-400 hover:text-zinc-100"
                    }`}
                  >
                    {t === "preview" ? "🌐 معاينة" : "📄 الكود"}
                  </button>
                ))}
              </div>
            </div>

            {/* Screen */}
            <div className="relative rounded-2xl overflow-hidden bg-black ring-2 ring-zinc-700/80 shadow-inner aspect-video">
              {/* Scanlines overlay */}
              <div
                className="pointer-events-none absolute inset-0 z-10 opacity-[0.08] mix-blend-overlay"
                style={{
                  backgroundImage:
                    "repeating-linear-gradient(0deg, rgba(255,255,255,0.6) 0 1px, transparent 1px 3px)",
                }}
              />
              {/* Vignette */}
              <div className="pointer-events-none absolute inset-0 z-10 rounded-2xl shadow-[inset_0_0_120px_rgba(0,0,0,0.65)]" />

              {!html ? (
                <div className="absolute inset-0 flex flex-col items-center justify-center text-zinc-400">
                  <div className="text-5xl mb-3 animate-pulse">📺</div>
                  <p className="text-sm">اضغط « 🚀 توليد الموقع » لعرض النتيجة هنا</p>
                </div>
              ) : tab === "preview" ? (
                <iframe
                  ref={iframeRef}
                  src={previewSrc}
                  title="preview"
                  className="absolute inset-0 w-full h-full bg-white"
                  sandbox="allow-scripts allow-forms allow-modals"
                />
              ) : (
                <pre className="absolute inset-0 overflow-auto p-4 text-xs bg-zinc-950 text-emerald-300 font-mono leading-relaxed">
                  <code>{html}</code>
                </pre>
              )}
            </div>

            {/* TV stand */}
            <div className="flex justify-between items-center mt-3 px-2 text-[11px] text-zinc-400 font-mono">
              <span>CH-01 · AR/EN</span>
              <span>{html ? `${(html.length / 1024).toFixed(1)} KB` : "—"}</span>
            </div>
          </div>
          <div className="mx-auto mt-2 h-3 w-40 bg-gradient-to-b from-zinc-700 to-zinc-900 rounded-b-xl" />
          <div className="mx-auto h-1 w-56 bg-zinc-800 rounded-full" />
        </section>
      </main>

      <footer className="text-center text-xs text-slate-500 py-6">
        مولّد مواقع ذكي — يدعم العربية والإنجليزية · بدون خادم، يعمل بالكامل في متصفحك.
      </footer>
    </div>
  );
}
