import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";
import JSZip from "jszip";
import FileSaver from "file-saver";
const { saveAs } = FileSaver;
import { useServerFn } from "@tanstack/react-start";
import { generateWebsite, type TemplateName } from "@/lib/website-generator";
import {
  listProjects,
  saveProject,
  deleteProject,
  type Project,
} from "@/lib/projects-store";
import { analyzeWebsite } from "@/lib/analyze.functions";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "مصمم المواقع الذكي | Smart Website Designer" },
      {
        name: "description",
        content:
          "صف موقعك بالعربية أو الإنجليزية واحصل على HTML جاهز فوراً مع معاينة مباشرة، قوالب متعددة، حفظ المشاريع وتصديرها كـ ZIP.",
      },
      { property: "og:title", content: "مصمم المواقع الذكي" },
      {
        property: "og:description",
        content: "ولّد مواقع جاهزة من وصف نصي مع معاينة فورية وتصدير ZIP.",
      },
    ],
  }),
  component: Index,
});

const EXAMPLES = [
  "موقع لمطعم عربي يحتوي على شريط علوي وقائمة طعام وصور ونموذج تواصل، باللون الأخضر",
  "Landing page for a SaaS product with hero, features cards, pricing table and contact form",
  "موقع شركة تقنية باللون الأزرق مع قائمة خدمات ومعرض صور وتذييل",
];

function Index() {
  const [mode, setMode] = useState<"create" | "describe">("create");
  const [lang, setLang] = useState<"ar" | "en">("ar");
  const [description, setDescription] = useState<string>(EXAMPLES[0]);
  const [template, setTemplate] = useState<TemplateName>("default");
  const [html, setHtml] = useState<string>("");
  const [projects, setProjects] = useState<Project[]>([]);
  const [projectName, setProjectName] = useState<string>("");
  const [tab, setTab] = useState<"preview" | "code" | "projects">("preview");
  const iframeRef = useRef<HTMLIFrameElement>(null);

  // Describe-existing-site state
  const [siteUrl, setSiteUrl] = useState<string>("");
  const [imageDataUrl, setImageDataUrl] = useState<string>("");
  const [analysis, setAnalysis] = useState<string>("");
  const [analyzing, setAnalyzing] = useState<boolean>(false);
  const [analyzeError, setAnalyzeError] = useState<string>("");
  const runAnalyze = useServerFn(analyzeWebsite);

  useEffect(() => {
    setProjects(listProjects());
    handleGenerate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleGenerate = () => {
    const code = generateWebsite(description, template);
    setHtml(code);
  };

  const onPickImage = (file: File | null) => {
    if (!file) {
      setImageDataUrl("");
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      setAnalyzeError(lang === "ar" ? "الصورة كبيرة جداً (الحد 5MB)" : "Image too large (max 5MB)");
      return;
    }
    const reader = new FileReader();
    reader.onload = () => setImageDataUrl(String(reader.result || ""));
    reader.readAsDataURL(file);
  };

  const handleAnalyze = async () => {
    setAnalyzeError("");
    setAnalysis("");
    if (!siteUrl.trim() && !imageDataUrl) {
      setAnalyzeError(lang === "ar" ? "أدخل رابطاً أو ارفع صورة" : "Enter a URL or upload an image");
      return;
    }
    setAnalyzing(true);
    try {
      const res = await runAnalyze({
        data: { url: siteUrl.trim(), imageDataUrl, lang },
      });
      setAnalysis(res.description || "");
    } catch (e) {
      setAnalyzeError((e as Error).message || "Error");
    } finally {
      setAnalyzing(false);
    }
  };

  const handleSave = () => {
    const name = projectName.trim() || description.slice(0, 40) || "مشروع";
    const p: Project = {
      id: crypto.randomUUID(),
      name,
      description,
      template,
      html,
      createdAt: Date.now(),
    };
    saveProject(p);
    setProjects(listProjects());
    setProjectName("");
  };

  const handleLoad = (p: Project) => {
    setDescription(p.description);
    setTemplate(p.template as TemplateName);
    setHtml(p.html);
    setTab("preview");
  };

  const handleDelete = (id: string) => {
    deleteProject(id);
    setProjects(listProjects());
  };

  const handleExportZip = async (p?: Project) => {
    const target = p ?? {
      name: projectName.trim() || "website",
      html,
      description,
    };
    const zip = new JSZip();
    zip.file("index.html", target.html);
    zip.file("description.txt", target.description);
    zip.file(
      "README.md",
      `# ${target.name}\n\nGenerated by Smart Website Designer.\n\nOpen \`index.html\` in any browser.\n`,
    );
    const blob = await zip.generateAsync({ type: "blob" });
    saveAs(blob, `${target.name.replace(/[^a-zA-Z0-9\u0600-\u06FF_-]+/g, "_")}.zip`);
  };

  const handleDownloadHtml = () => {
    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    saveAs(blob, "index.html");
  };

  const handleOpenInNewTab = () => {
    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    window.open(url, "_blank");
    setTimeout(() => URL.revokeObjectURL(url), 60_000);
  };

  const previewSrc = useMemo(() => {
    return "data:text/html;charset=utf-8," + encodeURIComponent(html);
  }, [html]);

  return (
    <div className="min-h-screen" style={{ background: "radial-gradient(ellipse at 50% 0%, #1a1a1a 0%, #0a0a0a 40%, #000000 100%)" }}>
      {/* Header */}
      <header className="border-b border-zinc-800 bg-black/70 backdrop-blur sticky top-0 z-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center text-white font-bold shadow-lg shadow-blue-500/30">
              W
            </div>
            <div>
              <h1 className="text-base sm:text-lg font-bold text-white">
                مصمم المواقع الذكي
              </h1>
              <p className="text-xs text-zinc-300">
                Smart Website Designer · AR / EN
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Link
              to="/ai-lab"
              className="text-sm px-3 py-2 rounded-lg bg-gradient-to-br from-fuchsia-500 to-indigo-600 text-white shadow-md hover:opacity-95"
            >
              🧠 مختبر الذكاء
            </Link>
            <button
              onClick={handleOpenInNewTab}
              disabled={!html}
              className="hidden sm:inline-flex text-sm px-3 py-2 rounded-lg border border-zinc-600 bg-zinc-900/60 text-white hover:bg-zinc-800 disabled:opacity-60 disabled:text-zinc-400"
            >
              فتح في نافذة
            </button>
            <button
              onClick={handleDownloadHtml}
              disabled={!html}
              className="text-sm px-3 py-2 rounded-lg border border-zinc-600 bg-zinc-900/60 text-white hover:bg-zinc-800 disabled:opacity-60 disabled:text-zinc-400"
            >
              HTML
            </button>
            <button
              onClick={() => handleExportZip()}
              disabled={!html}
              className="text-sm px-3 py-2 rounded-lg bg-white text-black font-semibold hover:bg-zinc-200 disabled:opacity-60 disabled:text-zinc-500"
            >
              تصدير ZIP
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-[1500px] mx-auto px-4 sm:px-6 py-6 flex flex-col lg:flex-row-reverse gap-6">
        {/* Description panel — right side on large screens */}
        <aside className="space-y-4 order-2 lg:order-1 w-full lg:w-1/3 lg:max-w-md">

          <div className="bg-zinc-900 rounded-2xl border border-zinc-800 p-5 shadow-sm">
            {/* Mode + Language toggles */}
            <div className="flex items-center justify-between gap-2 mb-3">
              <div className="flex bg-zinc-950 rounded-lg p-0.5 border border-zinc-800">
                <button
                  onClick={() => setMode("create")}
                  className={`text-xs px-2.5 py-1.5 rounded-md font-medium transition ${
                    mode === "create" ? "bg-blue-600 text-white" : "text-zinc-400 hover:text-zinc-200"
                  }`}
                >
                  🎨 تصميم جديد
                </button>
                <button
                  onClick={() => setMode("describe")}
                  className={`text-xs px-2.5 py-1.5 rounded-md font-medium transition ${
                    mode === "describe" ? "bg-blue-600 text-white" : "text-zinc-400 hover:text-zinc-200"
                  }`}
                >
                  🔍 وصف موقع موجود
                </button>
              </div>
              <div className="flex bg-zinc-950 rounded-lg p-0.5 border border-zinc-800">
                <button
                  onClick={() => setLang("ar")}
                  className={`text-xs px-2 py-1 rounded ${lang === "ar" ? "bg-zinc-200 text-zinc-900" : "text-zinc-400"}`}
                >
                  AR
                </button>
                <button
                  onClick={() => setLang("en")}
                  className={`text-xs px-2 py-1 rounded ${lang === "en" ? "bg-zinc-200 text-zinc-900" : "text-zinc-400"}`}
                >
                  EN
                </button>
              </div>
            </div>

            {mode === "create" ? (
              <>
                <label className="block text-sm font-semibold text-zinc-100 mb-2">
                  &nbsp;{lang === "ar" ? "صف موقعك (عربي أو إنجليزي)" : "Describe your website"}
                </label>
                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  rows={6}
                  dir={lang === "ar" ? "rtl" : "ltr"}
                  className="w-full text-sm rounded-xl border border-zinc-700 bg-zinc-950 text-zinc-100 p-3 focus:border-blue-500 focus:ring-2 focus:ring-blue-900 outline-none resize-none placeholder:text-zinc-500"
                  placeholder={lang === "ar"
                    ? "مثال: موقع لمطعم باللون الأخضر مع شريط علوي ونموذج تواصل..."
                    : "Example: A SaaS landing page with hero, features and pricing..."}
                />

                <div className="flex flex-wrap gap-2 mt-2">
                  {EXAMPLES.map((ex, i) => (
                    <button
                      key={i}
                      onClick={() => setDescription(ex)}
                      className="text-xs px-2.5 py-1 rounded-full bg-zinc-800 hover:bg-zinc-700 text-zinc-200"
                    >
                      {lang === "ar" ? "مثال" : "Example"} {i + 1}
                    </button>
                  ))}
                </div>

                <div className="grid grid-cols-2 gap-3 mt-4">
                  <div>
                    <label className="block text-xs font-medium text-zinc-300 mb-1">🎨 {lang === "ar" ? "القالب" : "Template"}</label>
                    <select
                      value={template}
                      onChange={(e) => setTemplate(e.target.value as TemplateName)}
                      className="w-full text-sm rounded-lg border border-zinc-700 px-3 py-2 bg-zinc-950 text-zinc-100"
                    >
                      <option value="default">Default (Modern)</option>
                      <option value="bootstrap">Bootstrap 5</option>
                      <option value="tailwind">Tailwind CDN</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-zinc-300 mb-1">💾 {lang === "ar" ? "اسم المشروع" : "Project name"}</label>
                    <input
                      value={projectName}
                      onChange={(e) => setProjectName(e.target.value)}
                      placeholder="my-site"
                      className="w-full text-sm rounded-lg border border-zinc-700 px-3 py-2 bg-zinc-950 text-zinc-100 placeholder:text-zinc-500"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-2 mt-4">
                  <button
                    onClick={handleGenerate}
                    className="text-sm font-semibold px-4 py-2.5 rounded-xl bg-gradient-to-br from-blue-600 to-indigo-600 text-white shadow-md shadow-blue-500/30 hover:opacity-95"
                  >
                    🚀 {lang === "ar" ? "توليد الموقع" : "Generate"}
                  </button>
                  <button
                    onClick={handleSave}
                    disabled={!html}
                    className="text-sm font-semibold px-4 py-2.5 rounded-xl bg-amber-500 text-white shadow-md shadow-amber-500/30 hover:bg-amber-600 disabled:opacity-60 disabled:text-zinc-300"
                  >
                    💾 {lang === "ar" ? "حفظ" : "Save"}
                  </button>
                </div>
              </>
            ) : (
              <>
                <label className="block text-sm font-semibold text-zinc-100 mb-2">
                  🔍 {lang === "ar" ? "حلّل موقعاً موجوداً" : "Analyze an existing site"}
                </label>

                <input
                  type="url"
                  value={siteUrl}
                  onChange={(e) => setSiteUrl(e.target.value)}
                  placeholder="https://example.com"
                  dir="ltr"
                  className="w-full text-sm rounded-lg border border-zinc-700 bg-zinc-950 text-zinc-100 px-3 py-2 focus:border-blue-500 outline-none placeholder:text-zinc-500"
                />

                <div className="mt-3">
                  <label className="block text-xs font-medium text-zinc-300 mb-1">
                    🖼️ {lang === "ar" ? "أو ارفع صورة لواجهة الموقع" : "Or upload a UI screenshot"}
                  </label>
                  <input
                    type="file"
                    accept="image/*"
                    onChange={(e) => onPickImage(e.target.files?.[0] || null)}
                    className="w-full text-xs text-zinc-300 file:mr-2 file:py-1.5 file:px-3 file:rounded-md file:border-0 file:text-xs file:bg-zinc-800 file:text-zinc-100 hover:file:bg-zinc-700"
                  />
                  {imageDataUrl && (
                    <img src={imageDataUrl} alt="upload" className="mt-2 max-h-32 rounded-md border border-zinc-800" />
                  )}
                </div>

                <button
                  onClick={handleAnalyze}
                  disabled={analyzing}
                  className="w-full mt-4 text-sm font-semibold px-4 py-2.5 rounded-xl bg-gradient-to-br from-fuchsia-600 to-indigo-600 text-white shadow-md hover:opacity-95 disabled:opacity-60"
                >
                  {analyzing
                    ? (lang === "ar" ? "⏳ جاري التحليل..." : "⏳ Analyzing...")
                    : (lang === "ar" ? "🧠 تحليل ووصف الموقع" : "🧠 Analyze & describe")}
                </button>

                {analyzeError && (
                  <p className="mt-2 text-xs text-red-400">{analyzeError}</p>
                )}

                {analysis && (
                  <div
                    dir={lang === "ar" ? "rtl" : "ltr"}
                    className="mt-3 max-h-80 overflow-auto text-xs leading-relaxed bg-zinc-950 border border-zinc-800 rounded-lg p-3 text-zinc-200 whitespace-pre-wrap"
                  >
                    {analysis}
                  </div>
                )}
              </>
            )}
          </div>

          <div className="bg-zinc-900 rounded-2xl border border-zinc-800 p-5 shadow-sm">
            <h3 className="text-sm font-semibold text-zinc-100 mb-2">
              💼 المشاريع المحفوظة ({projects.length})
            </h3>
            {projects.length === 0 ? (
              <p className="text-xs text-zinc-400 py-4 text-center">
                لا توجد مشاريع بعد. ولّد موقعاً واضغط حفظ.
              </p>
            ) : (
              <ul className="space-y-2 max-h-72 overflow-auto -mx-1 px-1">
                {projects.map((p) => (
                  <li
                    key={p.id}
                    className="border border-zinc-800 rounded-lg p-2.5 hover:bg-zinc-800 group"
                  >
                    <div className="flex items-center justify-between gap-2">
                      <button
                        onClick={() => handleLoad(p)}
                        className="text-sm font-medium text-zinc-100 text-right truncate flex-1"
                      >
                        {p.name}
                      </button>
                      <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                        <button
                          onClick={() => handleExportZip(p)}
                          title="تصدير"
                          className="text-xs px-2 py-1 rounded hover:bg-zinc-700 text-zinc-300"
                        >
                          📦
                        </button>
                        <button
                          onClick={() => handleDelete(p.id)}
                          title="حذف"
                          className="text-xs px-2 py-1 rounded hover:bg-red-900/30 text-red-400"
                        >
                          🗑
                        </button>
                      </div>
                    </div>
                    <p className="text-[11px] text-zinc-400 mt-0.5 truncate">
                      {p.template} · {new Date(p.createdAt).toLocaleString()}
                    </p>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </aside>

        {/* TV — full width, above the description */}
        <section className="order-1 lg:order-2 flex flex-col w-full lg:flex-1 lg:min-w-0">


          {/* Outer box — deepest frame with rim light */}
          <div
            className="relative rounded-2xl p-1 border border-black shadow-[0_25px_60px_-20px_rgba(0,0,0,0.95),inset_0_2px_0_rgba(255,255,255,0.18),inset_0_-2px_0_rgba(0,0,0,0.92),inset_2.5px_0_0_rgba(255,255,255,0.12),inset_-2.5px_0_0_rgba(0,0,0,0.85)]"
            style={{
              background:
                "radial-gradient(120% 90% at 50% 0%, #181818 0%, #080808 50%, #020202 100%)",
            }}
          >
            {/* Subtle wavy highlight band along the top inner edge */}
            <span
              aria-hidden
              className="pointer-events-none absolute inset-x-1 top-0 h-[4px] rounded-t-2xl opacity-80"
              style={{
                background:
                  "linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.28) 20%, rgba(255,255,255,0.06) 50%, rgba(255,255,255,0.28) 80%, transparent 100%)",
              }}
            />
            {/* Outer box corner bolts — metallic */}
            <span className="absolute top-0.5 left-0.5 w-1.5 h-1.5 rounded-full bg-gradient-to-br from-zinc-300 to-zinc-700 shadow-[0_0_3px_rgba(0,0,0,0.95),inset_0_1px_0_rgba(255,255,255,0.5)]" />
            <span className="absolute top-0.5 right-0.5 w-1.5 h-1.5 rounded-full bg-gradient-to-br from-zinc-300 to-zinc-700 shadow-[0_0_3px_rgba(0,0,0,0.95),inset_0_1px_0_rgba(255,255,255,0.5)]" />
            <span className="absolute bottom-0.5 left-0.5 w-1.5 h-1.5 rounded-full bg-gradient-to-br from-zinc-300 to-zinc-700 shadow-[0_0_3px_rgba(0,0,0,0.95),inset_0_1px_0_rgba(255,255,255,0.5)]" />
            <span className="absolute bottom-0.5 right-0.5 w-1.5 h-1.5 rounded-full bg-gradient-to-br from-zinc-300 to-zinc-700 shadow-[0_0_3px_rgba(0,0,0,0.95),inset_0_1px_0_rgba(255,255,255,0.5)]" />

            {/* Middle box — brushed metal */}
            <div
              className="relative rounded-xl p-1 border border-zinc-900/80 shadow-[inset_0_2px_0_rgba(255,255,255,0.22),inset_0_-2px_0_rgba(0,0,0,0.95),inset_2px_0_0_rgba(255,255,255,0.1),inset_-2px_0_0_rgba(0,0,0,0.85),0_4px_10px_-4px_rgba(0,0,0,0.75)]"
              style={{
                background:
                  "linear-gradient(180deg, #1a1a1a 0%, #0a0a0a 55%, #121212 100%)",
              }}
            >
              <span
                aria-hidden
                className="pointer-events-none absolute inset-x-2 top-0 h-[2px] opacity-90"
                style={{
                  background:
                    "linear-gradient(90deg, transparent, rgba(255,255,255,0.45) 30%, rgba(255,255,255,0.12) 50%, rgba(255,255,255,0.45) 70%, transparent)",
                }}
              />
              {/* Inner box (TV body) — glossy bezel */}
              <div
                className="relative rounded-lg p-2 border border-zinc-800/70 shadow-[0_12px_30px_-10px_rgba(0,0,0,0.95),inset_0_2px_0_rgba(255,255,255,0.24),inset_0_-2px_4px_rgba(0,0,0,0.98),inset_2px_0_0_rgba(255,255,255,0.1),inset_-2px_0_0_rgba(0,0,0,0.88)]"
                style={{
                  background:
                    "linear-gradient(180deg, #0c0c0c 0%, #000 45%, #040404 100%)",
                }}
              >
                <span
                  aria-hidden
                  className="pointer-events-none absolute inset-x-1.5 top-0 h-[2px] opacity-95"
                  style={{
                    background:
                      "linear-gradient(90deg, transparent, rgba(255,255,255,0.5) 25%, rgba(255,255,255,0.18) 50%, rgba(255,255,255,0.5) 75%, transparent)",
                  }}
                />
                {/* TV bezel top controls */}
                <div className="flex items-center justify-between mb-2 px-1">
                  <div className="flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-red-600 shadow-[0_0_6px_rgba(220,38,38,0.6)]" />
                    <span className="w-2 h-2 rounded-full bg-yellow-500" />
                    <span className="w-2 h-2 rounded-full bg-green-600" />
                    <span className="ml-1.5 text-[10px] text-zinc-400 font-mono">LIVE · شاشة المعاينة</span>
                  </div>
                  <div className="flex gap-1 bg-zinc-950 rounded-md p-0.5">
                    {(["preview", "code"] as const).map((t) => (
                      <button
                        key={t}
                        onClick={() => setTab(t)}
                        className={`text-[11px] px-2 py-0.5 rounded font-medium transition ${
                          tab === t
                            ? "bg-zinc-200 text-zinc-900"
                            : "text-zinc-400 hover:text-zinc-200"
                        }`}
                      >
                        {t === "preview" ? "🌐 معاينة" : "📄 الكود"}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Screen */}
                <div className="relative rounded-lg overflow-hidden bg-black ring-1 ring-zinc-800 shadow-inner aspect-video">
                  <div
                    className="pointer-events-none absolute inset-0 z-10 opacity-[0.06] mix-blend-overlay"
                    style={{
                      backgroundImage:
                        "repeating-linear-gradient(0deg, rgba(255,255,255,0.5) 0 1px, transparent 1px 3px)",
                    }}
                  />
                  <div className="pointer-events-none absolute inset-0 z-10 rounded-lg shadow-[inset_0_0_80px_rgba(0,0,0,0.6)]" />

                  {!html ? (
                    <div className="absolute inset-0 flex flex-col items-center justify-center text-zinc-400">
                      <div className="text-4xl mb-2 animate-pulse">📺</div>
                      <p className="text-xs">اضغط « 🚀 توليد الموقع » لعرض النتيجة هنا</p>
                    </div>
                  ) : tab === "preview" ? (
                    <iframe
                      ref={iframeRef}
                      src={previewSrc}
                      title="preview"
                      className="absolute inset-0 w-full h-full bg-white"
                      sandbox="allow-scripts allow-forms allow-modals"
                    />
                  ) : (
                    <pre className="absolute inset-0 overflow-auto p-3 text-[11px] bg-zinc-950 text-emerald-300 font-mono leading-relaxed">
                      <code>{html}</code>
                    </pre>
                  )}
                </div>

                {/* TV info bar */}
                <div className="flex justify-between items-center mt-2 px-1 text-[10px] text-zinc-600 font-mono">
                  <span>CH-01 · AR/EN</span>
                  <span>{html ? `${(html.length / 1024).toFixed(1)} KB` : "—"}</span>
                </div>
              </div>
            </div>
          </div>

          {/* Stand */}
          <div className="mx-auto mt-1 h-2 w-28 bg-gradient-to-b from-zinc-900 to-black rounded-b-lg shadow-md" />
          <div className="mx-auto h-1 w-48 bg-black rounded-full shadow-md" />
        </section>
      </main>

      <footer className="text-center text-xs text-zinc-400 py-6">
        مولّد مواقع ذكي — يدعم العربية والإنجليزية · بدون خادم، يعمل بالكامل في متصفحك.
      </footer>
    </div>
  );
}
